version: '3'
services:
  backend-api:
    image: node-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - allNet
    depends_on:
      - redis
  redis:
    image: "redis/redis-stack-server:latest"
    ports:
      - "6379:6379"
    networks:
      - allNet

networks:
  allNet:
