version: '3'

services:
  backend-api:
    build:
      context: .
      dockerfile: Dockerfile  # Replace with your actual Dockerfile name
    ports:
      - "3000:3000"
    networks:
      - allNet

networks:
  allNet:
