version: '3'

services:
  backend-api:
    image: node-backend
    build:
      context: .
      dockerfile: DockerfileBackend
    ports:
      - "3000:3000"
    networks:
      - allNet

networks:
  allNet:
